import './js/firebase';
import './js/login/logout';
import './js/mobile-menu';
import './js/header';
import './js/shoppinglist-darkmode';
import './js/support';
import './js/shopping-list';
import './js/clock';
import './js/pagination';
